name: cross build

on:
  push:
    paths:
      - "src/**"
      - "Cargo.*"
      - ".github/workflows/cross-build.yml"

jobs:
  linux-musl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-musl
          - i386-unknown-linux-musl
          - riscv64gc-unknown-linux-musl
        rustflags:
          - ""
        include:
          - target: i686-unknown-linux-musl
            rustflags: "-C target-feature=+sse2"
          - target: i386-unknown-linux-musl
            rustflags: "-C target-feature=+sse2"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}
      - run: sudo apt-get update && sudo apt-get install -y libiio-dev
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.target }}
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.2
      - run: cargo install cargo-zigbuild --locked
      - run: cargo zigbuild --release --target ${{ matrix.target }}
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
      - uses: actions/upload-artifact@v4
        with:
          name: yured-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/yured

  freebsd:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            target: x86_64-unknown-freebsd
          - arch: aarch64
            target: aarch64-unknown-freebsd
          - arch: riscv64
            target: riscv64gc-unknown-freebsd
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        with:
          arch: ${{ matrix.arch }}
          usesh: true
          prepare: |
            pkg install -y curl git
            pkg install -y libiio
            curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly
          run: |
            . "$HOME/.cargo/env"
            rustup target add ${{ matrix.target }}
            cargo build --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: yured-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/yured
